package com.zz.we.mapper;

import com.zz.we.dto.Chat;
import com.zz.we.dto.ChatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    long countByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    int deleteByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    int insert(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    int insertSelective(Chat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    List<Chat> selectByExample(ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Chat record, @Param("example") ChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    int updateByExample(@Param("record") Chat record, @Param("example") ChatExample example);
}