package com.zz.we.mapper;

import com.zz.we.dto.MyUser;
import com.zz.we.dto.MyUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    long countByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    int deleteByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    int insert(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    int insertSelective(MyUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    List<MyUser> selectByExample(MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") MyUser record, @Param("example") MyUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myuser
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    int updateByExample(@Param("record") MyUser record, @Param("example") MyUserExample example);
}