package com.zz.we.mapper;

import com.zz.we.dto.Photos;
import com.zz.we.dto.PhotosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhotosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    long countByExample(PhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    int deleteByExample(PhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    int insert(Photos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    int insertSelective(Photos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    List<Photos> selectByExample(PhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    int updateByExampleSelective(@Param("record") Photos record, @Param("example") PhotosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photos
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    int updateByExample(@Param("record") Photos record, @Param("example") PhotosExample example);
}