package com.zz.we.mapper;

import com.zz.we.dto.Praise;
import com.zz.we.dto.PraiseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PraiseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    long countByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    int deleteByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    int insert(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    int insertSelective(Praise record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    List<Praise> selectByExample(PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Praise record, @Param("example") PraiseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table praise
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    int updateByExample(@Param("record") Praise record, @Param("example") PraiseExample example);
}