package com.zz.we.mapper;

import com.zz.we.dto.SlideList;
import com.zz.we.dto.SlideListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SlideListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideList
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    long countByExample(SlideListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideList
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    int deleteByExample(SlideListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideList
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    int insert(SlideList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideList
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    int insertSelective(SlideList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideList
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    List<SlideList> selectByExample(SlideListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideList
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") SlideList record, @Param("example") SlideListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideList
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    int updateByExample(@Param("record") SlideList record, @Param("example") SlideListExample example);
}