package com.zz.we.dto;

import java.util.Date;

public class Chat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.appid
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.nickname
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.face
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    private String face;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.name
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.tel
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.plan
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    private String plan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.extra
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    private String extra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.requestTime
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    private Date requesttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat.updateTime
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.appid
     *
     * @return the value of chat.appid
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.appid
     *
     * @param appid the value for chat.appid
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.nickname
     *
     * @return the value of chat.nickname
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.nickname
     *
     * @param nickname the value for chat.nickname
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.face
     *
     * @return the value of chat.face
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.face
     *
     * @param face the value for chat.face
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public void setFace(String face) {
        this.face = face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.name
     *
     * @return the value of chat.name
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.name
     *
     * @param name the value for chat.name
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.tel
     *
     * @return the value of chat.tel
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.tel
     *
     * @param tel the value for chat.tel
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.plan
     *
     * @return the value of chat.plan
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public String getPlan() {
        return plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.plan
     *
     * @param plan the value for chat.plan
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public void setPlan(String plan) {
        this.plan = plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.extra
     *
     * @return the value of chat.extra
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.extra
     *
     * @param extra the value for chat.extra
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public void setExtra(String extra) {
        this.extra = extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.requestTime
     *
     * @return the value of chat.requestTime
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public Date getRequesttime() {
        return requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.requestTime
     *
     * @param requesttime the value for chat.requestTime
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public void setRequesttime(Date requesttime) {
        this.requesttime = requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat.updateTime
     *
     * @return the value of chat.updateTime
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat.updateTime
     *
     * @param updatetime the value for chat.updateTime
     *
     * @mbg.generated Sun Jun 02 19:10:08 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}