package com.zz.we.dto;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.appid
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.nickname
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.face
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    private String face;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.words
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    private String words;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.time
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.update
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    private Date update;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.appid
     *
     * @return the value of comment.appid
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.appid
     *
     * @param appid the value for comment.appid
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.nickname
     *
     * @return the value of comment.nickname
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.nickname
     *
     * @param nickname the value for comment.nickname
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.face
     *
     * @return the value of comment.face
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.face
     *
     * @param face the value for comment.face
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public void setFace(String face) {
        this.face = face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.words
     *
     * @return the value of comment.words
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public String getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.words
     *
     * @param words the value for comment.words
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public void setWords(String words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.time
     *
     * @return the value of comment.time
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.time
     *
     * @param time the value for comment.time
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.update
     *
     * @return the value of comment.update
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public Date getUpdate() {
        return update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.update
     *
     * @param update the value for comment.update
     *
     * @mbg.generated Sun Jun 02 12:29:13 CST 2019
     */
    public void setUpdate(Date update) {
        this.update = update;
    }
}