package com.zz.we.dto;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.appid
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.nickname
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.face
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    private String face;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.words
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    private String words;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.requestTime
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    private String requesttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.updateTime
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    private String updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.appid
     *
     * @return the value of comment.appid
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.appid
     *
     * @param appid the value for comment.appid
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.nickname
     *
     * @return the value of comment.nickname
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.nickname
     *
     * @param nickname the value for comment.nickname
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.face
     *
     * @return the value of comment.face
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.face
     *
     * @param face the value for comment.face
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public void setFace(String face) {
        this.face = face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.words
     *
     * @return the value of comment.words
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public String getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.words
     *
     * @param words the value for comment.words
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public void setWords(String words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.requestTime
     *
     * @return the value of comment.requestTime
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public String getRequesttime() {
        return requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.requestTime
     *
     * @param requesttime the value for comment.requestTime
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public void setRequesttime(String requesttime) {
        this.requesttime = requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.updateTime
     *
     * @return the value of comment.updateTime
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.updateTime
     *
     * @param updatetime the value for comment.updateTime
     *
     * @mbg.generated Sun Jun 02 19:49:23 CST 2019
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime;
    }
}