package com.zz.we.dto;

import java.util.Date;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.face
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String face;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.nickname
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.time
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.words
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String words;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.image
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item.appid
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String appid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.face
     *
     * @return the value of item.face
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.face
     *
     * @param face the value for item.face
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setFace(String face) {
        this.face = face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.nickname
     *
     * @return the value of item.nickname
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.nickname
     *
     * @param nickname the value for item.nickname
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.time
     *
     * @return the value of item.time
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.time
     *
     * @param time the value for item.time
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.words
     *
     * @return the value of item.words
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getWords() {
        return words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.words
     *
     * @param words the value for item.words
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setWords(String words) {
        this.words = words;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.image
     *
     * @return the value of item.image
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.image
     *
     * @param image the value for item.image
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item.appid
     *
     * @return the value of item.appid
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item.appid
     *
     * @param appid the value for item.appid
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }
}