package com.zz.we.dto;

import java.util.Date;

public class MainInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.cover
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String cover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.he
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String he;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.she
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String she;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.date
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.lunar
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String lunar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.hotel
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String hotel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.address
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.appid
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.lng
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mainInfo.lat
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.cover
     *
     * @return the value of mainInfo.cover
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.cover
     *
     * @param cover the value for mainInfo.cover
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setCover(String cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.he
     *
     * @return the value of mainInfo.he
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getHe() {
        return he;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.he
     *
     * @param he the value for mainInfo.he
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setHe(String he) {
        this.he = he;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.she
     *
     * @return the value of mainInfo.she
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getShe() {
        return she;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.she
     *
     * @param she the value for mainInfo.she
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setShe(String she) {
        this.she = she;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.date
     *
     * @return the value of mainInfo.date
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.date
     *
     * @param date the value for mainInfo.date
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.lunar
     *
     * @return the value of mainInfo.lunar
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getLunar() {
        return lunar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.lunar
     *
     * @param lunar the value for mainInfo.lunar
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setLunar(String lunar) {
        this.lunar = lunar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.hotel
     *
     * @return the value of mainInfo.hotel
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getHotel() {
        return hotel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.hotel
     *
     * @param hotel the value for mainInfo.hotel
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setHotel(String hotel) {
        this.hotel = hotel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.address
     *
     * @return the value of mainInfo.address
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.address
     *
     * @param address the value for mainInfo.address
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.appid
     *
     * @return the value of mainInfo.appid
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.appid
     *
     * @param appid the value for mainInfo.appid
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.lng
     *
     * @return the value of mainInfo.lng
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.lng
     *
     * @param lng the value for mainInfo.lng
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setLng(String lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mainInfo.lat
     *
     * @return the value of mainInfo.lat
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mainInfo.lat
     *
     * @param lat the value for mainInfo.lat
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setLat(String lat) {
        this.lat = lat;
    }
}