package com.zz.we.dto;

public class Mmap {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.lng
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.lat
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.hetel
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    private String hetel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.shetel
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    private String shetel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.he
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    private String he;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.she
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    private String she;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column map.appid
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    private String appid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.lng
     *
     * @return the value of map.lng
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.lng
     *
     * @param lng the value for map.lng
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void setLng(String lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.lat
     *
     * @return the value of map.lat
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.lat
     *
     * @param lat the value for map.lat
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void setLat(String lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.hetel
     *
     * @return the value of map.hetel
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public String getHetel() {
        return hetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.hetel
     *
     * @param hetel the value for map.hetel
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void setHetel(String hetel) {
        this.hetel = hetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.shetel
     *
     * @return the value of map.shetel
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public String getShetel() {
        return shetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.shetel
     *
     * @param shetel the value for map.shetel
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void setShetel(String shetel) {
        this.shetel = shetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.he
     *
     * @return the value of map.he
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public String getHe() {
        return he;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.he
     *
     * @param he the value for map.he
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void setHe(String he) {
        this.he = he;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.she
     *
     * @return the value of map.she
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public String getShe() {
        return she;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.she
     *
     * @param she the value for map.she
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void setShe(String she) {
        this.she = she;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column map.appid
     *
     * @return the value of map.appid
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column map.appid
     *
     * @param appid the value for map.appid
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }
}