package com.zz.we.dto;

import java.util.ArrayList;
import java.util.List;

public class MmapExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public MmapExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLngIsNull() {
            addCriterion("lng is null");
            return (Criteria) this;
        }

        public Criteria andLngIsNotNull() {
            addCriterion("lng is not null");
            return (Criteria) this;
        }

        public Criteria andLngEqualTo(String value) {
            addCriterion("lng =", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotEqualTo(String value) {
            addCriterion("lng <>", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThan(String value) {
            addCriterion("lng >", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThanOrEqualTo(String value) {
            addCriterion("lng >=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThan(String value) {
            addCriterion("lng <", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThanOrEqualTo(String value) {
            addCriterion("lng <=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLike(String value) {
            addCriterion("lng like", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotLike(String value) {
            addCriterion("lng not like", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngIn(List<String> values) {
            addCriterion("lng in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotIn(List<String> values) {
            addCriterion("lng not in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngBetween(String value1, String value2) {
            addCriterion("lng between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotBetween(String value1, String value2) {
            addCriterion("lng not between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andLatIsNull() {
            addCriterion("lat is null");
            return (Criteria) this;
        }

        public Criteria andLatIsNotNull() {
            addCriterion("lat is not null");
            return (Criteria) this;
        }

        public Criteria andLatEqualTo(String value) {
            addCriterion("lat =", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotEqualTo(String value) {
            addCriterion("lat <>", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThan(String value) {
            addCriterion("lat >", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThanOrEqualTo(String value) {
            addCriterion("lat >=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThan(String value) {
            addCriterion("lat <", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThanOrEqualTo(String value) {
            addCriterion("lat <=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLike(String value) {
            addCriterion("lat like", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotLike(String value) {
            addCriterion("lat not like", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatIn(List<String> values) {
            addCriterion("lat in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotIn(List<String> values) {
            addCriterion("lat not in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatBetween(String value1, String value2) {
            addCriterion("lat between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotBetween(String value1, String value2) {
            addCriterion("lat not between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andHetelIsNull() {
            addCriterion("hetel is null");
            return (Criteria) this;
        }

        public Criteria andHetelIsNotNull() {
            addCriterion("hetel is not null");
            return (Criteria) this;
        }

        public Criteria andHetelEqualTo(String value) {
            addCriterion("hetel =", value, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelNotEqualTo(String value) {
            addCriterion("hetel <>", value, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelGreaterThan(String value) {
            addCriterion("hetel >", value, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelGreaterThanOrEqualTo(String value) {
            addCriterion("hetel >=", value, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelLessThan(String value) {
            addCriterion("hetel <", value, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelLessThanOrEqualTo(String value) {
            addCriterion("hetel <=", value, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelLike(String value) {
            addCriterion("hetel like", value, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelNotLike(String value) {
            addCriterion("hetel not like", value, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelIn(List<String> values) {
            addCriterion("hetel in", values, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelNotIn(List<String> values) {
            addCriterion("hetel not in", values, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelBetween(String value1, String value2) {
            addCriterion("hetel between", value1, value2, "hetel");
            return (Criteria) this;
        }

        public Criteria andHetelNotBetween(String value1, String value2) {
            addCriterion("hetel not between", value1, value2, "hetel");
            return (Criteria) this;
        }

        public Criteria andShetelIsNull() {
            addCriterion("shetel is null");
            return (Criteria) this;
        }

        public Criteria andShetelIsNotNull() {
            addCriterion("shetel is not null");
            return (Criteria) this;
        }

        public Criteria andShetelEqualTo(String value) {
            addCriterion("shetel =", value, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelNotEqualTo(String value) {
            addCriterion("shetel <>", value, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelGreaterThan(String value) {
            addCriterion("shetel >", value, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelGreaterThanOrEqualTo(String value) {
            addCriterion("shetel >=", value, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelLessThan(String value) {
            addCriterion("shetel <", value, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelLessThanOrEqualTo(String value) {
            addCriterion("shetel <=", value, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelLike(String value) {
            addCriterion("shetel like", value, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelNotLike(String value) {
            addCriterion("shetel not like", value, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelIn(List<String> values) {
            addCriterion("shetel in", values, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelNotIn(List<String> values) {
            addCriterion("shetel not in", values, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelBetween(String value1, String value2) {
            addCriterion("shetel between", value1, value2, "shetel");
            return (Criteria) this;
        }

        public Criteria andShetelNotBetween(String value1, String value2) {
            addCriterion("shetel not between", value1, value2, "shetel");
            return (Criteria) this;
        }

        public Criteria andHeIsNull() {
            addCriterion("he is null");
            return (Criteria) this;
        }

        public Criteria andHeIsNotNull() {
            addCriterion("he is not null");
            return (Criteria) this;
        }

        public Criteria andHeEqualTo(String value) {
            addCriterion("he =", value, "he");
            return (Criteria) this;
        }

        public Criteria andHeNotEqualTo(String value) {
            addCriterion("he <>", value, "he");
            return (Criteria) this;
        }

        public Criteria andHeGreaterThan(String value) {
            addCriterion("he >", value, "he");
            return (Criteria) this;
        }

        public Criteria andHeGreaterThanOrEqualTo(String value) {
            addCriterion("he >=", value, "he");
            return (Criteria) this;
        }

        public Criteria andHeLessThan(String value) {
            addCriterion("he <", value, "he");
            return (Criteria) this;
        }

        public Criteria andHeLessThanOrEqualTo(String value) {
            addCriterion("he <=", value, "he");
            return (Criteria) this;
        }

        public Criteria andHeLike(String value) {
            addCriterion("he like", value, "he");
            return (Criteria) this;
        }

        public Criteria andHeNotLike(String value) {
            addCriterion("he not like", value, "he");
            return (Criteria) this;
        }

        public Criteria andHeIn(List<String> values) {
            addCriterion("he in", values, "he");
            return (Criteria) this;
        }

        public Criteria andHeNotIn(List<String> values) {
            addCriterion("he not in", values, "he");
            return (Criteria) this;
        }

        public Criteria andHeBetween(String value1, String value2) {
            addCriterion("he between", value1, value2, "he");
            return (Criteria) this;
        }

        public Criteria andHeNotBetween(String value1, String value2) {
            addCriterion("he not between", value1, value2, "he");
            return (Criteria) this;
        }

        public Criteria andSheIsNull() {
            addCriterion("she is null");
            return (Criteria) this;
        }

        public Criteria andSheIsNotNull() {
            addCriterion("she is not null");
            return (Criteria) this;
        }

        public Criteria andSheEqualTo(String value) {
            addCriterion("she =", value, "she");
            return (Criteria) this;
        }

        public Criteria andSheNotEqualTo(String value) {
            addCriterion("she <>", value, "she");
            return (Criteria) this;
        }

        public Criteria andSheGreaterThan(String value) {
            addCriterion("she >", value, "she");
            return (Criteria) this;
        }

        public Criteria andSheGreaterThanOrEqualTo(String value) {
            addCriterion("she >=", value, "she");
            return (Criteria) this;
        }

        public Criteria andSheLessThan(String value) {
            addCriterion("she <", value, "she");
            return (Criteria) this;
        }

        public Criteria andSheLessThanOrEqualTo(String value) {
            addCriterion("she <=", value, "she");
            return (Criteria) this;
        }

        public Criteria andSheLike(String value) {
            addCriterion("she like", value, "she");
            return (Criteria) this;
        }

        public Criteria andSheNotLike(String value) {
            addCriterion("she not like", value, "she");
            return (Criteria) this;
        }

        public Criteria andSheIn(List<String> values) {
            addCriterion("she in", values, "she");
            return (Criteria) this;
        }

        public Criteria andSheNotIn(List<String> values) {
            addCriterion("she not in", values, "she");
            return (Criteria) this;
        }

        public Criteria andSheBetween(String value1, String value2) {
            addCriterion("she between", value1, value2, "she");
            return (Criteria) this;
        }

        public Criteria andSheNotBetween(String value1, String value2) {
            addCriterion("she not between", value1, value2, "she");
            return (Criteria) this;
        }

        public Criteria andAppidIsNull() {
            addCriterion("appid is null");
            return (Criteria) this;
        }

        public Criteria andAppidIsNotNull() {
            addCriterion("appid is not null");
            return (Criteria) this;
        }

        public Criteria andAppidEqualTo(String value) {
            addCriterion("appid =", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotEqualTo(String value) {
            addCriterion("appid <>", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThan(String value) {
            addCriterion("appid >", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidGreaterThanOrEqualTo(String value) {
            addCriterion("appid >=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThan(String value) {
            addCriterion("appid <", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLessThanOrEqualTo(String value) {
            addCriterion("appid <=", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidLike(String value) {
            addCriterion("appid like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotLike(String value) {
            addCriterion("appid not like", value, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidIn(List<String> values) {
            addCriterion("appid in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotIn(List<String> values) {
            addCriterion("appid not in", values, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidBetween(String value1, String value2) {
            addCriterion("appid between", value1, value2, "appid");
            return (Criteria) this;
        }

        public Criteria andAppidNotBetween(String value1, String value2) {
            addCriterion("appid not between", value1, value2, "appid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table map
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 03 17:58:49 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table map
     *
     * @mbg.generated Mon Jun 03 17:58:49 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}