package com.zz.we.dto;

public class MyUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.account
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.password
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myuser.appid
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    private String appid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.account
     *
     * @return the value of myuser.account
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.account
     *
     * @param account the value for myuser.account
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.password
     *
     * @return the value of myuser.password
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.password
     *
     * @param password the value for myuser.password
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myuser.appid
     *
     * @return the value of myuser.appid
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myuser.appid
     *
     * @param appid the value for myuser.appid
     *
     * @mbg.generated Tue Jun 04 19:06:02 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }
}