package com.zz.we.dto;

public class Photos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.appid
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.alt
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    private String alt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.pid
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.src
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    private String src;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photos.thumb
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    private String thumb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.appid
     *
     * @return the value of photos.appid
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.appid
     *
     * @param appid the value for photos.appid
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.alt
     *
     * @return the value of photos.alt
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public String getAlt() {
        return alt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.alt
     *
     * @param alt the value for photos.alt
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public void setAlt(String alt) {
        this.alt = alt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.pid
     *
     * @return the value of photos.pid
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.pid
     *
     * @param pid the value for photos.pid
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.src
     *
     * @return the value of photos.src
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public String getSrc() {
        return src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.src
     *
     * @param src the value for photos.src
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public void setSrc(String src) {
        this.src = src;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photos.thumb
     *
     * @return the value of photos.thumb
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photos.thumb
     *
     * @param thumb the value for photos.thumb
     *
     * @mbg.generated Thu Jun 13 16:15:31 CST 2019
     */
    public void setThumb(String thumb) {
        this.thumb = thumb;
    }
}