package com.zz.we.dto;

public class Praise {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.appid
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.face
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    private String face;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.nickname
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column praise.requestTime
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    private String requesttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.appid
     *
     * @return the value of praise.appid
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.appid
     *
     * @param appid the value for praise.appid
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.face
     *
     * @return the value of praise.face
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.face
     *
     * @param face the value for praise.face
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    public void setFace(String face) {
        this.face = face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.nickname
     *
     * @return the value of praise.nickname
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.nickname
     *
     * @param nickname the value for praise.nickname
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column praise.requestTime
     *
     * @return the value of praise.requestTime
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    public String getRequesttime() {
        return requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column praise.requestTime
     *
     * @param requesttime the value for praise.requestTime
     *
     * @mbg.generated Sun Jun 02 20:27:02 CST 2019
     */
    public void setRequesttime(String requesttime) {
        this.requesttime = requesttime;
    }
}