package com.zz.we.dto;

public class SlideList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideList.image
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideList.appid
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    private String appid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideList.image
     *
     * @return the value of slideList.image
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideList.image
     *
     * @param image the value for slideList.image
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideList.appid
     *
     * @return the value of slideList.appid
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideList.appid
     *
     * @param appid the value for slideList.appid
     *
     * @mbg.generated Wed May 22 18:29:57 CST 2019
     */
    public void setAppid(String appid) {
        this.appid = appid;
    }
}